apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
      strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  partitions: 12
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic-reversed
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  partitions: 12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-hello-world-producer
  name: kafka-hello-world-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-hello-world-producer
  template:
    metadata:
      labels:
        app: kafka-hello-world-producer
    spec:
      containers:
      - name: kafka-hello-world-producer
        image: strimzi/hello-world-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: k8s-css-nprod-kafka-bootstrap.streaming:9092
          - name: TOPIC
            value: my-topic
          - name: DELAY_MS
            value: "5000"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: JAEGER_SERVICE_NAME
            value: kafka-hello-world-producer
          - name: JAEGER_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-hello-world-streams
  name: kafka-hello-world-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-hello-world-streams
  template:
    metadata:
      labels:
        app: kafka-hello-world-streams
    spec:
      containers:
        - name: kafka-hello-world-streams
          image: strimzi/hello-world-streams:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: k8s-css-nprod-kafka-bootstrap.streaming:9092
            - name: APPLICATION_ID
              value: kafka-hello-world-streams
            - name: SOURCE_TOPIC
              value: my-topic
            - name: TARGET_TOPIC
              value: my-topic-reversed
            - name: LOG_LEVEL
              value: "INFO"
            - name: JAEGER_SERVICE_NAME
              value: kafka-hello-world-streams
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-hello-world-consumer
  name: kafka-hello-world-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-hello-world-consumer
  template:
    metadata:
      labels:
        app: kafka-hello-world-consumer
    spec:
      containers:
        - name: kafka-hello-world-consumer
          image: strimzi/hello-world-consumer:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: k8s-css-nprod-kafka-bootstrap.streaming:9092
            - name: TOPIC
              value: my-topic-reversed
            - name: GROUP_ID
              value: kafka-hello-world-consumer
            - name: LOG_LEVEL
              value: "INFO"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: JAEGER_SERVICE_NAME
              value: kafka-hello-world-consumer
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
